# Welcome to Jekyll!
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lyx-Foodie
email: kekeyun728@gmail.com
description: Love yourself - get food, get heavier.
keywords: jekyll, bootstrap, jekyll-site, jekyll-website, html, bootstrap4, bootstrap-4, bootstrap-theme, bootstrap-template, portfolio-website, portfolio-theme, open-source, free, google-anaytics, github-pages

baseurl: "https://returnless.github.io/Lyx-Foodie/" # the subpath of your site, e.g. /blog
url: "https://returnless.github.io/Lyx-Foodie/" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  returnless
google_analytics_tracking_id: UA
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
incremental: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
#exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include: ['.htaccess']
